name: jitsi_meet_platform_interface
description: A common platform interface for the jitsi meet plugin.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

